@contentType = application/json
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJzIjoiNjIxNDJmMjlhYTFkZDRiMmM3OThkY2UxIiwibmFtZSI6IlJvZ2dlciBPcnRpeiIsInVzZXJuYW1lIjoicm9ydGl6IiwiZW1haWwiOiJyb2dnZXIub3J0aXouYnJAZ21haWwuY29tIiwicmVmcmVzaFRva2VuIjoiMjNlNzU3ODgtYzY2Yy00MmI5LWE4MTMtMjY5OWRhNGE3NGY4IiwiaWF0IjoxNjQ1NTE4ODU1LCJleHAiOjE2NDU2MDUyNTV9.TduoCrFDPDbG1sl_ahfEN7wKCLVW9cXZ-irhJBVaKlg

###

POST http://localhost:4000/api/auth/signup HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Juan Perez",
    "username": "jperez",
    "email": "jperez@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4000/api/auth/signin HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "jperez@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4000/api/auth/refreshtoken HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
    "refreshToken": "23e75788-c66c-42b9-a813-2699da4a74f8"
}